spring:
  config:
    activate:
      on-profile:
  datasource:
    url: "jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 20000
            readTimeout: 20000

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /3o3/swagger.html
  api-docs:
    path: /3o3

jwt:
  expire_time: 86400000 #1day
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

aes256:
  key: myassingmentkey!

scrap:
  x-api-key: asdasdsadasdsa